-- ─────────────────────────────────────────────────────────────────────────────
-- CTO Savings Intelligence — three tables
--
--  cto_savings_config    : one row per app — base costs + outsourced breakdown
--  cto_savings_inflation : one row per calendar year — annual inflation rate %
--  cto_savings_cache     : pre-computed totals written by the Lambda
-- ─────────────────────────────────────────────────────────────────────────────

-- 1. App config ───────────────────────────────────────────────────────────────
create table if not exists public.cto_savings_config (
  id                    bigint generated by default as identity primary key,
  app_key               text not null unique,           -- e.g. 'stellar-ops'
  app_name              text not null,                  -- display name
  app_description       text not null,                  -- one-liner
  our_cost_monthly      numeric(10,2) not null,         -- INR/month (our AWS share)
  outsourced_saas       numeric(10,2) not null default 0, -- SaaS tools cost INR/month
  outsourced_agency     numeric(10,2) not null default 0, -- agency/freelancer INR/month
  outsourced_engineer   numeric(10,2) not null default 0, -- fractional engineer INR/month
  outsourced_llm        numeric(10,2) not null default 0, -- OpenAI/Azure equivalent INR/month
  outsourced_legend     text not null,                  -- comma-separated "what this covers"
  launch_date           date not null,                  -- when this app went live
  is_active             boolean not null default true,
  sort_order            int not null default 0,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- 2. Inflation config ─────────────────────────────────────────────────────────
create table if not exists public.cto_savings_inflation (
  id            bigint generated by default as identity primary key,
  year          int not null unique,        -- calendar year e.g. 2024
  rate_pct      numeric(5,2) not null,     -- e.g. 10.00 = 10% YoY salary/market inflation
  notes         text,
  created_at    timestamptz not null default now()
);

-- 3. Computed cache ───────────────────────────────────────────────────────────
create table if not exists public.cto_savings_cache (
  id                    bigint generated by default as identity primary key,
  computed_at           timestamptz not null default now(),

  -- Monthly (current month, with inflation applied to current year)
  monthly_our_cost      numeric(12,2) not null,
  monthly_outsourced    numeric(12,2) not null,
  monthly_saving        numeric(12,2) not null,

  -- Yearly (12 × current inflated monthly)
  yearly_our_cost       numeric(12,2) not null,
  yearly_outsourced     numeric(12,2) not null,
  yearly_saving         numeric(12,2) not null,

  -- Till date (sum of all months since each app launched, with per-year inflation)
  tilldate_our_cost     numeric(12,2) not null,
  tilldate_outsourced   numeric(12,2) not null,
  tilldate_saving       numeric(12,2) not null,
  tilldate_months       int not null,

  -- Per-app breakdown snapshot (jsonb array of {app_key, app_name, our_cost, outsourced_total, saving, legend})
  app_breakdown         jsonb not null default '[]'::jsonb
);

-- Only ever keep the single most-recent row
create unique index if not exists cto_savings_cache_singleton
  on public.cto_savings_cache ((true));

-- ─── RLS ─────────────────────────────────────────────────────────────────────
alter table public.cto_savings_config     enable row level security;
alter table public.cto_savings_inflation  enable row level security;
alter table public.cto_savings_cache      enable row level security;

create policy "Authenticated users can read savings config"
  on public.cto_savings_config for select to authenticated using (true);

create policy "Authenticated users can read savings inflation"
  on public.cto_savings_inflation for select to authenticated using (true);

create policy "Authenticated users can read savings cache"
  on public.cto_savings_cache for select to authenticated using (true);

create policy "Service role full access savings config"
  on public.cto_savings_config for all to service_role using (true) with check (true);

create policy "Service role full access savings inflation"
  on public.cto_savings_inflation for all to service_role using (true) with check (true);

create policy "Service role full access savings cache"
  on public.cto_savings_cache for all to service_role using (true) with check (true);

-- ─── Seed: app config ────────────────────────────────────────────────────────
-- All amounts in INR/month. Launch date = 2026-05-01 (2 months ago).
-- Our costs are fractional shares of the ₹83/month total AWS+Bedrock bill.
-- Update these rows any time via Supabase dashboard or SQL — the Lambda will
-- pick up changes on next run.

insert into public.cto_savings_config
  (app_key, app_name, app_description,
   our_cost_monthly,
   outsourced_saas, outsourced_agency, outsourced_engineer, outsourced_llm,
   outsourced_legend, launch_date, sort_order)
values
  ('stellar-ops',
   'Stellar Ops Platform',
   'Sales, purchase, GST data · 6 AI agents · Meta analytics · Document drive · Centralised dashboard',
   20,
   8000,  -- Zoho CRM ₹5K + Zoho Books ₹3K
   40000, -- Custom ERP agency retainer
   50000, -- 0.5× senior engineer @ ₹1L/mo
   8000,  -- Azure OpenAI equivalent for 6 chatbot agents
   'Zoho CRM + Zoho Books, Custom ERP agency retainer, 0.5× senior engineer, Azure OpenAI / ChatBot SaaS (6 agents)',
   '2026-05-01', 1),

  ('stellar-oms',
   'Stellar OMS',
   'Order lifecycle management · Client delivery tracking · Status automation',
   8,
   12000, -- Unicommerce or custom OMS SaaS
   0,
   30000, -- 0.3× engineer
   0,
   'Unicommerce / custom OMS SaaS, 0.3× senior engineer',
   '2026-05-01', 2),

  ('stellar-quote',
   'Stellar Quote System',
   'Quote generation · Draft → saved → shared → preview → convert to order lifecycle',
   5,
   6000,  -- PandaDoc / Zoho Quotes
   0,
   20000, -- 0.2× engineer
   0,
   'PandaDoc / Zoho Quotes license, 0.2× senior engineer',
   '2026-05-01', 3),

  ('stellar-workflow',
   'Stellar Workflow Platform',
   'AI lead gen · LinkedIn/Facebook/Instagram posts · Email drafts · Blog writing · Human-in-loop approvals',
   25,
   3000,  -- Mailchimp / email tool
   30000, -- Social media agency
   50000, -- 0.5× engineer
   15000, -- LLM costs for content generation (OpenAI equivalent)
   'Social media agency (posts + blogs), Mailchimp / email automation, 0.5× senior engineer, OpenAI API equivalent for content',
   '2026-05-01', 4),

  ('stellar-observe',
   'Stellar Observe Platform',
   'AWS infra monitoring · Lambda/API/Step Fn metrics · Supabase health · Web traffic · Cost reports · Cleanups',
   8,
   20000, -- Datadog equivalent
   5000,  -- AWS cost monitoring tool (CloudHealth / Spot.io)
   20000, -- 0.2× DevOps engineer
   0,
   'Datadog / New Relic, AWS cost management tool (CloudHealth), 0.2× DevOps engineer',
   '2026-05-01', 5),

  ('stellar-confluence',
   'Stellar Confluence',
   'AI-generated knowledge base · Auto-maintained docs · Atlassian-style wiki on custom stack',
   5,
   3000,  -- Atlassian Confluence Cloud
   15000, -- Technical writer retainer
   10000, -- 0.1× engineer
   0,
   'Atlassian Confluence Cloud license, Technical writer retainer, 0.1× engineer',
   '2026-05-01', 6),

  ('stellar-website',
   'Stellar Website',
   'B2B industrial website · Designed and built solo · Same AWS stack · SEO optimised',
   5,
   0,
   15000, -- Web design agency monthly maintenance retainer
   10000, -- 0.1× frontend engineer
   0,
   'Web design agency (build amortised + monthly maintenance), 0.1× frontend engineer',
   '2026-05-01', 7),

  ('stellar-chatbot',
   'AI Chatbot — 6 Agents',
   'Sales analyst · Business analyst · Strategist · Demand forecaster · Marketing manager · Executive assistant',
   8,
   25000, -- ChatBot SaaS platform
   20000, -- Prompt engineer / AI specialist retainer
   30000, -- 0.3× engineer
   0,
   'ChatBot SaaS platform, Prompt engineer / AI specialist retainer, 0.3× engineer',
   '2026-05-01', 8);

-- ─── Seed: inflation rates ────────────────────────────────────────────────────
-- 10% is a conservative Indian market salary + SaaS pricing inflation rate.
-- Add a new row each year — the Lambda applies compound inflation automatically.
insert into public.cto_savings_inflation (year, rate_pct, notes) values
  (2024, 10.00, 'Base year — Indian market salary inflation ~10%'),
  (2025, 10.00, 'Estimated — update after CPI/salary surveys'),
  (2026, 10.00, 'Estimated — update after CPI/salary surveys');